#!/usr/bin/ruby
# Generates message.json from the files.

require 'rubygems'
require 'json'

puts '{'

ARGV.each do |file|
  File.read(file).scan(/__MSG_(.+?)__/) do |m|
    puts '  "%s": {' % m[0]
    puts '    "message": "",'
    puts '    "description": ""'
    puts '  },'
  end
end

puts '}'
